name: Deploy to production

on:
  push:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io
    
jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: print-stuff
      run: |
        env
        pwd
        ls -lahrt
        
    - name: Build and push
      run: |
        echo ${{ secrets.BUILD_PAT }} | docker login $REGISTRY -u ${{ github.repository_owner }} --password-stdin
        docker build . -t $REGISTRY/${{ github.repository}}:latest
        docker push $REGISTRY/${{ github.repository}}:latest
